config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, :only => [:show]

  root 'exams#index'

  resources :exams do
    resources :questions do
      resources :choices
    end
  end
  

end

app/models/choice.rb
class Choice < ActiveRecord::Base
	belongs_to :question
end

app/models/exam.rb
class Exam < ActiveRecord::Base
    has_many :questions
    accepts_nested_attributes_for :questions, :reject_if => :all_blank, :allow_destroy => true

end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :choices
      belongs_to :exam
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  def create
    @choice = Choice.new(choice_params)
  end

  def new
    @choice = Choice.new
  end

  def show
  end

  def update
    @choice = Choice.find(params[:id])
    if @choice.update(choice_params)
      redirect_to @choice
    else
      render :edit, notice: "failure"
    end
  end

  def destroy
    
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController

  def index
    @exam = Exam.all
  end

  def new
    @exam = Exam.new  
    3.times { @exam.questions.build }
  end

  def create
      @exam = Exam.new(exam_params)
        @exam.save
        redirect_to @exam, notice: 'Post was successfully created.' 
  end

  def show
     @exam = Exam.find(params[:id])
  end

  def edit
    @exam = Exam.find(params[:id])
  end

  def update
      @exam = Exam.find(params[:id])

        @exam.update_attributes(exam_params)
        redirect_to root_path
  end

    def destroy
      @exam = Exam.find(params[:id])
    @exam.destroy 
    redirect_to root_path
  end

  private 
   def exam_params
      params.require(:exam).permit(:name, :descriptions, questions_attributes: [:question, :exam_id] )
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    # def set_exam
    #   params[:exam]
    # end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # def create
  #    @question = Question.new(question_params)
   
  #   if @question.save
  #     redirect_to @question
  #   else
  #     render 'new'
  #   end
  # end

  def create
    @exam = Exam.find(params[:exam_id])
    @question = @exam.questions.create(question_params)
    if@question.save
      redirect_to exam_path(@exam)
    else
      render :new
    end
    #redirect_to post_path(@post)
  end

  def new
    @question = Question.new
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = Queston.find(params[:id])
  end

  def update
     @exam = Exam.find(params[:exam_id])
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit, notice: "failure"
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:question, :exam_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def destroy
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/choices/create.html.erb
<h1>Choices#create</h1>
<p>Find me in app/views/choices/create.html.erb</p>

app/views/choices/destroy.html.erb
<h1>Choices#destroy</h1>
<p>Find me in app/views/choices/destroy.html.erb</p>

app/views/choices/new.html.erb
<h1>Choices#new</h1>
<p>Find me in app/views/choices/new.html.erb</p>

app/views/choices/show.html.erb
<h1>Choices#show</h1>
<p>Find me in app/views/choices/show.html.erb</p>

app/views/choices/update.html.erb
<h1>Choices#update</h1>
<p>Find me in app/views/choices/update.html.erb</p>

app/views/exams/_form.html.erb
<%= form_for(@exam) do |f| %>
  <% if @exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% @exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class='large-8 large-centered columns'>
  <h1>New Quiz</h1>
  <%= f.label :name%>
  <%= f.text_field :name, class: "nametext", rows: "7"%>

  <%= f.label :descriptions%>
  <%= f.text_area :descriptions, class: "destext", rows: "4"%>


  <h1>Add Questions</h1>


  <%= f.fields_for :questions do |builder| %>
  <p>
    <%= builder.label :question, "Question" %><br />
    <%= builder.text_area :question, :rows => 3 %>
  </p>
  <% end %>
</div>
  
  <div class="actions">
    <%= f.submit "Update Quiz", class: 'button large-centered small-2 submit' %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<h1>Edit Exam</h1>

<%= render 'form' %>
<div class='Back'>
<%= link_to 'Show', @exam, class: 'button' %> 
<%= link_to 'Back', exams_path, class: 'button '%>
</div>

app/views/exams/index.html.erb
<h2 class='large-1 large-centered columns'>Quizes</h2>
<div class='large-8 large-centered columns'>
  <% @exam.each do |exam| %>
   <ul class="pricing-table">
    <li class="title titleexam"><h3>Name: <%= exam.name %></h3></li>
    <p>Description: <br> <%= exam.descriptions %></p>
    <div class='exam_options'>
        <%= link_to 'Show', exam_path(exam.id), class: 'button' %>
        <%= link_to 'Edit', edit_exam_path(exam.id), class: 'button' %>
        <%= link_to 'Delete Quiz', exam, method: :delete, class: 'button'%>
    </div>
   </ul>  
  <% end %>
  <hr>
</div>
<div class='Back'>
<%= link_to 'New Quiz', new_exam_path, class: 'button large-2 large-centered'%>
</div>

app/views/exams/new.html.erb
<%= render 'form' %>
<div class='Back'>
<%= link_to 'Back', exams_path, class: 'button small-2' %>
</div>

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @exam.name %></h1>

<h3>Description:</h3>
<p><%= @exam.descriptions %></p>
<h4>Questions:</h4>
<% @exam.questions.each do |question| %>
  <h2><%= question.question %></h2>
<% end %>


<div class='Back'>
<%= link_to 'Edit', edit_exam_path(@exam), class: 'button'%> 
<%= link_to 'Back', exams_path, class: 'button' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Quizler" %></title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
       <nav class="top-bar" data-topbar role="navigation">
          <ul class="title-area">
            <li class="name">
              <h1><%= link_to 'Quizler',root_path, class: "title"%></h1>
            </li>
             <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
            <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
          </ul>

          <section class="top-bar-section">
            <!-- Right Nav Section -->
            <ul class="right">
              <li class="has-dropdown">
                    <a href="#">log In</a>
                    <ul class="dropdown">
                      <% if user_signed_in? %>
                        <li>Signed in as <%= current_user.email %> Not you?</li>
                        <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                      <% else %>
                        <li><%= link_to "Sign up", new_user_registration_path %></li>
                        <li class="active"><%= link_to "Sign in", new_user_session_path %></li>
                      <% end %>
                    </ul>
              </li>
            </ul>
          </section>
        </nav>
    </header>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/edit.html.erb
<h1>Questions#edit</h1>
<p>Find me in app/views/questions/edit.html.erb</p>

app/views/questions/new.html.erb
<h1>Questions#new</h1>
<p>Find me in app/views/questions/new.html.erb</p>

app/views/questions/show.html.erb
<h1>Questions#show</h1>
<p>Find me in app/views/questions/show.html.erb</p>

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>